### ISSUE TITLE
where it the RobotGoalsArray.h?

### ISSUE THREAD

**Issue by sunjiaming2018** [tuw-robotics/tuw_multi_robot#11]
when  i try to use this demo and catkin_make,it show
`/home/sun/catkin_ws/src/tuw_multi_robot/tuw_multi_robot_goal_generator/include/tuw_multi_robot_goal_generator/multi_robot_goal_handler.h:5:10: fatal error: tuw_multi_robot_msgs/RobotGoalsArray.h: No such file or directory
 #include "tuw_multi_robot_msgs/RobotGoalsArray.h"`
I can not find the head File. How to solved it?
Tanks for your much!

**Comment by axelbr** [comment]
Hi!
You will need to clone and build the tuw_msgs repository (https://github.com/tuw-robotics/tuw_msgs). The messages (such as RobotGoalsArray) are located there.
Best regards, Axel

**Comment by axelbr** [comment]
Please reopen it, if this does not solve this error.
