### ISSUE TITLE
Graph Visualization bug

### ISSUE THREAD

**Issue by saikishor** [tuw-robotics/tuw_multi_robot#13]
With the new MR merged into the upstream, there is currently the graph visualization issue, the graph seems to be scaled and shifted from the map.

**Comment by axelbr** [comment]
the visualization should work. the rviz plugins have been updated too. are you sure you built the whole workspace with the new update? have a look at the tuw_multi_robot_rviz package. the displays were updated accordingly to the other changes.

**Comment by saikishor** [comment]
Yes, It's a mistake on my end.
