### ISSUE TITLE
Multi Robot Router: Failed to find Routing Table !!!

### ISSUE THREAD

**Issue by saikishor** [tuw-robotics/tuw_multi_robot#14]
I observed at most of the time with the multi robot simulation, when i give the goals very nearby, I end up having the error : `Multi Robot Router: Failed to find Routing Table !!!`. For instance, for 3 robots, when I given 3 goals very nearby, it is finding the plan for 2 robots, and it is failing on the 3rd robot step at the computation of the potentials. Any idea?

**Comment by axelbr** [comment]
could you provide a screenshot of the goal poses?

**Comment by saikishor** [comment]
![image](https://user-images.githubusercontent.com/10082428/62131152-e7052700-b2da-11e9-9bf1-e537b8adf254.png)
The goal poses are as simple as this.

**Comment by saikishor** [comment]
@axelbr any idea?. I guess in this case it is finding the successor from the collision resolver and getting into the loop, so thereby not finding the solutions in the given cycles.

**Comment by axelbr** [comment]
i will have a look at it later. maybe there must be at least one segment between a robot and its goal. @maxbader maybe you know whats the issue here.

**Comment by saikishor** [comment]
@axelbr I don't think so, this happens always when you give three consecutive goals at a distance of one or two segments, which can happen in real scenario. It will have the plan for first robot, but it messes up when computing the plan for the second or third robot.

**Comment by saikishor** [comment]
@maxbader can you comment on this issue please?

**Comment by qzlinqian** [comment]
I also found that when I used segments grid to define the graph, if the start position of some robots is a little close (maybe less than 0.24m for the robots with a radius of 0.04m), the same error also happened. But surprisingly when I use Voronoi graph, that won't happen...

**Comment by saikishor** [comment]
@qzlinqian so you mean this issue happens for you only with the grid type of graph but not the Voronoi graph?

**Comment by qzlinqian** [comment]
> @qzlinqian so you mean this issue happens for you only with the grid type of graph but not the Voronoi graph?

Yes. After I switched to Voronoi graph, the start/goal points can be close enough. I don't know whether it's because I didn't define the segments correctly or the voronoi-segment-to-graph-node hasn't been fully tested.
