### ISSUE TITLE
How to use existing individual controllers running on each vehicle such as DWA implemented in move_base?

### ISSUE THREAD

**Issue by anshulasimov** [tuw-robotics/tuw_multi_robot#18]
It is mentioned that the design allows the usage of existing individual controllers running on each vehicle such as DWA implemented in move_base. How does one go about this ?
Also can this package handle dynamic obstacles if encountered ? If No , what are the modifications that are required to be made

**Comment by maxbader** [comment]
Check the  graph on https://wiki.ros.org/tuw_multi_robot showing the framework. You have to interface with the local behavior controller. This is a hot and upcoming topic
