### ISSUE TITLE
Melodic release

### ISSUE THREAD

**Issue by gpdas** [tuw-robotics/tuw_multi_robot#22]
Hi,

Are there any plans to get this released for Melodic?

I was looking for a melodic release of packages in this repo. Since I couldn't find that, tried to build from source. However, the build failed as `tuw_local_controller_msgs` is missing. Also found the same issue in the build failure in Jenkins. 
http://build.ros.org/view/Mdev/job/Mdev__tuw_multi_robot__ubuntu_bionic_amd64/lastBuild/console

I checked the `tuw_msgs` repo, where `tuw_local_controller_msgs` is present in `master` branch but not in `melodic-devel` branch, which hasn't been updated for quite a long time. I am not sure from which branch melodic binaries for `tuw_msgs` are made.

Thanks

**Comment by maxbader** [comment]
At the moment, we have to less time to make a cleared commits for every new ROS version. The master branch should work.

**Comment by maxbader** [comment]
I just released a ROS noetic version
