### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by jaswanthmv** [tuw-robotics/tuw_multi_robot#24]
When cloned the repository and building the package, been facing a "make -j4 -l4" error about a missing "Route.h" file from tuw_multi_robot_msgs package.
I have already cloned the tuw_msgs, tuw_geometry packages inside the "src" folder and I am using ROS Melodic. Please refer to the screenshot pasted below for the error.
![image](https://user-images.githubusercontent.com/69240424/89394665-fb6bd300-d729-11ea-92e3-665983c721be.png)

**Comment by maxbader** [comment]
Please compile the tuw_msgs first. It looks like there is a problem on the order how to compile the system.

**Comment by jaswanthmv** [comment]
Thank you. Didn't know that. I have one more doubt. Can I use this library for controlling two or three robots. I understood that this library is for route planning but I also want task allocation and other features. Can you please help this novice?

**Comment by maxbader** [comment]
Yes, but you have to be more spezific. But please have a look at the paper https://ieeexplore.ieee.org/document/8968465 first,
B. Binder, F. Beck, F. König and M. Bader, "Multi Robot Route Planning (MRRP): Extended Spatial-Temporal Prioritized Planning," 2019 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), Macau, China, 2019, pp. 4133-4139, doi: 10.1109/IROS40897.2019.8968465.
