### ISSUE TITLE
ActionServer will set this goal to aborted

### ISSUE THREAD

**Issue by muratkayamurat** [tuw-robotics/tuw_multi_robot#25]
Hello there,
first of all thanks for the project. I have problem with ActionServer. I dont know why but some times, when i set the goal for the robots, there is an error on terminal :

"[ WARN] [1608201578.027515776]: Your executeCallback did not set the goal to a terminal status.
This is a bug in your ActionServer implementation. Fix your code!
For now, the ActionServer will set this goal to aborted"

and some robots stop.

I use ubuntu 18.04 and melodic.

Thanks,

**Comment by maxbader** [comment]
Can you reproduce the problem, can you post more details. I would appreciate if you can go to the noetic

**Comment by muratkayamurat** [comment]
I have to use melodic unfortunately,
i used your demo and at the first usage of goal selector everything is fine but second run with goal selector 

"[ WARN] [1608201578.027515776]: Your executeCallback did not set the goal to a terminal status.
This is a bug in your ActionServer implementation. Fix your code!
For now, the ActionServer will set this goal to aborted"

Warn shows up at terminal and then robots can not move correctly such as one of them stopped or going inside each others. 

![q](https://user-images.githubusercontent.com/16269069/102494559-e6169600-4085-11eb-8e08-6ec15c42771f.png)
![Screenshot from 2020-12-17 16-36-47](https://user-images.githubusercontent.com/16269069/102494759-368df380-4086-11eb-8271-0dad98e69f42.png)

**And the second problem is when i send goal positions nearly :**

[ INFO] [1608212342.463736848, 21.000000000]: Multi Robot Router: Failed to find Routing Table !!!
[ INFO] [1608212342.463776412, 21.000000000]: /multi_robot_router: No Plan found!!!!, publishing empty plan
[ INFO] [1608212342.463821527, 21.000000000]: 
Success 0, 1 = 0.000, avr   21 ms, success: -nan ms, PR= on, SR= on, CR= on 
 [0.000,   21,  -nan]

then robots dont move

![Screenshot from 2020-12-17 16-40-13](https://user-images.githubusercontent.com/16269069/102495003-984e5d80-4086-11eb-8dc1-86cc40b2eec7.png)
![Screenshot from 2020-12-17 16-40-54](https://user-images.githubusercontent.com/16269069/102495047-aac89700-4086-11eb-850f-d81dc19fb3a4.png)

Thanks for your interest :)

**Comment by maxbader** [comment]
Hi,
One question at a time
first the simple one: the current implementation needs at least one or two segments between goal endpoints.
second: @Your executeCallback I have need more input to get you a proper answer. contact me directly via email.

**Comment by bxc237** [comment]
Hi @maxbader, I also encountered a similar problem, the robot gets stuck and not trying to move at all or robots just go through (collide with) each other. I attach the video here (https://www.dropbox.com/s/p15etm5buafov62/tuw_multi_robot_problem.mp4?dl=0), could you help me with this issue? Thanks.
