### ISSUE TITLE
Default demo breaks in graph_generator node

### ISSUE THREAD

**Issue by sgermanserrano** [tuw-robotics/tuw_multi_robot#34]
Launching the default demo via
```
roslaunch tuw_multi_robot_demo demo.launch
```
or
```
roslaunch tuw_multi_robot_demo demo.launch room:=cave cfg:=robot_2
```
throws the following error
```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error-Resource temporarily unavailable
[graph_generator-4] process has died [pid 179999, exit code -6, cmd /home/servando/unipart/tuw_ups/install/tuw_voronoi_graph/lib/tuw_voronoi_graph/tuw_voronoi_graph_node __name:=graph_generator __log:=/home/servando/.ros/log/68558376-e318-11eb-8dbb-83f761b2ecc2/graph_generator-4.log].
log file: /home/servando/.ros/log/68558376-e318-11eb-8dbb-83f761b2ecc2/graph_generator-4*.log
```
I'm testing in Ubuntu 20.04 and ROS Noetic

**Comment by sgermanserrano** [comment]
#35 fixes this problem also

**Comment by kintzhao** [comment]
Has the same error on latest master

roslaunch tuw_multi_robot_demo demo.launch room:=cave cfg:=robot_2 
... logging to /home/robot/.ros/log/8bba7af8-15a0-11ee-b67c-91536b8574cd/roslaunch-robot-281072.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://robot:41473/

SUMMARY
========

PARAMETERS
 * /graph_generator/custom_graph_path: 
 * /graph_generator/graph_cache_path: /home/robot/my_pj...
 * /graph_generator/map_inflation: 0.1
 * /graph_generator/map_topic: /map
 * /graph_generator/opt_crossings: 0.2
 * /graph_generator/opt_end_segments: 0.5
 * /graph_generator/segment_length: 0.6
 * /graph_generator/segments_topic: /segments
 * /multi_robot_router/allow_endpoint_off_segments: True
 * /multi_robot_router/collision_resolver: 2
 * /multi_robot_router/path_optimization_segment_no: 1
 * /multi_robot_router/priority_rescheduling: True
 * /multi_robot_router/publish_routing_table: True
 * /multi_robot_router/speed_rescheduling: True
 * /multi_robot_router/use_segment_as_goal: False
 * /robot_0/local_behavior/robot_name: robot_0
 * /robot_0/local_behavior/robot_radius: 0.3
 * /robot_1/local_behavior/robot_name: robot_1
 * /robot_1/local_behavior/robot_radius: 0.3
 * /robot_2/local_behavior/robot_name: robot_2
 * /robot_2/local_behavior/robot_radius: 0.3
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    graph_generator (tuw_voronoi_graph/tuw_voronoi_graph_node)
    map_server (map_server/map_server)
    multi_robot_router (tuw_multi_robot_router/tuw_multi_robot_router_node)
    rviz (rviz/rviz)
    stageros (stage_ros/stageros)
  /robot_0/
    link1_broadcaster (tf2_ros/static_transform_publisher)
    local_behavior (tuw_multi_robot_local_behavior_controller/tuw_local_behavior_controller_node)
    self_localization (nodelet/nodelet)
    trajectory_controller (tuw_multi_robot_ctrl/tuw_velocity_controller)
  /robot_1/
    link1_broadcaster (tf2_ros/static_transform_publisher)
    local_behavior (tuw_multi_robot_local_behavior_controller/tuw_local_behavior_controller_node)
    self_localization (nodelet/nodelet)
    trajectory_controller (tuw_multi_robot_ctrl/tuw_velocity_controller)
  /robot_2/
    link1_broadcaster (tf2_ros/static_transform_publisher)
    local_behavior (tuw_multi_robot_local_behavior_controller/tuw_local_behavior_controller_node)
    self_localization (nodelet/nodelet)
    trajectory_controller (tuw_multi_robot_ctrl/tuw_velocity_controller)

auto-starting new master
process[master]: started with pid [281099]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8bba7af8-15a0-11ee-b67c-91536b8574cd
process[rosout-1]: started with pid [281128]
started core service [/rosout]
process[map_server-2]: started with pid [281135]
process[stageros-3]: started with pid [281136]
process[graph_generator-4]: started with pid [281137]
process[robot_2/link1_broadcaster-5]: started with pid [281138]
process[robot_2/trajectory_controller-6]: started with pid [281139]
process[robot_2/local_behavior-7]: started with pid [281140]
process[robot_2/self_localization-8]: started with pid [281156]
process[robot_1/link1_broadcaster-9]: started with pid [281163]
process[robot_1/trajectory_controller-10]: started with pid [281164]
process[robot_1/local_behavior-11]: started with pid [281171]
process[robot_1/self_localization-12]: started with pid [281178]
process[robot_0/link1_broadcaster-13]: started with pid [281184]
process[robot_0/trajectory_controller-14]: started with pid [281186]
process[robot_0/local_behavior-15]: started with pid [281192]
process[robot_0/self_localization-16]: started with pid [281219]
process[multi_robot_router-17]: started with pid [281228]
process[rviz-18]: started with pid [281233]
 [Loading /home/robot/my_pj/tuw-robotics_ws/src/tuw_multi_robot/tuw_multi_robot_demo/cfg/maps/cave/stage.world][ INFO] [1687948978.329542129]: Multi Robot Mode
[Image "map.pgm"[ INFO] [1687948978.356163396]: Initialization done!
[ INFO] [1687948978.359638625]: robot name = robot_2
[ INFO] [1687948978.360416175]: robot name = robot_1
[ INFO] [1687948978.365904716]: robot name = robot_0
]
[ INFO] [1687948978.460890874]: rviz version 1.14.20
[ INFO] [1687948978.460917990]: compiled against Qt version 5.12.8
[ INFO] [1687948978.460986955]: compiled against OGRE version 1.9.0 (Ghadamon)
[ INFO] [1687948978.467284447]: Forcing OpenGl version 0.
warn: worldfile /home/robot/my_pj/tuw-robotics_ws/src/tuw_multi_robot/tuw_multi_robot_demo/cfg/maps/cave/stage.world:19 : property [laser_return] is defined but not used (/tmp/binarydeb/ros-noetic-stage-4.3.0/libstage/worldfile.cc WarnUnused)
[ INFO] [1687948978.491662832]: Subscribed to Stage position model "robot_0"
[ INFO] [1687948978.492264563]: subscribed to Stage ranger "robot_0.ranger:0"
[ INFO] [1687948978.492271758]: Robot robot_0 provided 1 rangers and 0 cameras
[ INFO] [1687948978.494649731]: Subscribed to Stage position model "robot_1"
[ INFO] [1687948978.494660113]: subscribed to Stage ranger "robot_1.ranger:0"
[ INFO] [1687948978.494663587]: Robot robot_1 provided 1 rangers and 0 cameras
[ INFO] [1687948978.496092771]: Subscribed to Stage position model "robot_2"
[ INFO] [1687948978.496101841]: subscribed to Stage ranger "robot_2.ranger:0"
[ INFO] [1687948978.496106237]: Robot robot_2 provided 1 rangers and 0 cameras
[ INFO] [1687948978.996325598]: Stereo is NOT SUPPORTED
[ INFO] [1687948978.996367890]: OpenGL device: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
[ INFO] [1687948978.996385909]: OpenGl version: 4.6 (GLSL 4.6).
[ INFO] [1687948979.321677700]: map -8.000000 -8.000000 0.032000
[ INFO] [1687948979.328942052]: /multi_robot_router: New Map 500 500 7145731090466067206
[ INFO] [1687948979.467253836]: Creating 1 swatches
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error-Resource temporarily unavailable
[graph_generator-4] process has died [pid 281137, exit code -6, cmd /home/robot/my_pj/tuw-robotics_ws/devel/lib/tuw_voronoi_graph/tuw_voronoi_graph_node __name:=graph_generator __log:=/home/robot/.ros/log/8bba7af8-15a0-11ee-b67c-91536b8574cd/graph_generator-4.log].
log file: /home/robot/.ros/log/8bba7af8-15a0-11ee-b67c-91536b8574cd/graph_generator-4*.log


tuw_multi_robot$ git log  
commit 6863bf4f04c02e99f4bbe74fec48612f85125918 (HEAD -> master, origin/master, origin/HEAD)
Author: Markus Bader <markus.bader@tuwien.ac.at>
Date:   Fri Mar 4 10:56:43 2022 +0100

    Update README.md

commit 0754f57cffb656671d6018a0810dca86b8fab041
Merge: f0faa36 98e2275
Author: Markus Bader <markus.bader@tuwien.ac.at>
Date:   Tue Jul 20 08:30:55 2021 +0200

    Merge pull request #32 from LdwgWffnschmdt/master
    
    Enable building in isolation with --install flag

**Comment by esther-araujo** [comment]
@kintzhao 
Hello, I had the same problem when the node tries to load a pre save graph. It looks like an issue in reading the graph data with Boost C++ library. I did'nt find a better way to solve this, but what I am doing is forcing the node to always create a new graph, I removed the part that loads a pre saved graph.
I think this may help you.

**Comment by ahmetyuce526** [comment]
hi I have same problem, why anyone doesn't helping, 3-4 year passing but there is no solution ,,   "terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error-Resource temporarily unavailable
[graph_generator-4] process has died "

**Comment by deepConnectionism** [comment]
> @kintzhao Hello, I had the same problem when the node tries to load a pre save graph. It looks like an issue in reading the graph data with Boost C++ library. I did'nt find a better way to solve this, but what I am doing is forcing the node to always create a new graph, I removed the part that loads a pre saved graph.
@ahmetyuce526 

My environment is ubuntu20.04, noetic.

I also encountered the same problem. The problem is that when you run it for the first time, you will get the correct result, but when you run it again, you will encounter an error:

`boost::archive::archive_exception  what(): input stream error-Resource temporarily unavailable`

Open two terminals and the test commands are:

```
roslaunch tuw_multi_robot_demo demo.launch room:=warehouse200 nr_of_robots:=50
rosrun tuw_multi_robot_goal_generator goals_random _nr_of_robots:=50 _distance_boundary:=0.6 _distance_to_map_border:=0.2 _nr_of_avaliable_robots:=50
```
Reason:

It seems that the problem is caused by loading the first map. I just cleared the first map. The location is：

`src/tuw_multi_robot/tuw_multi_robot_demo/cfg/graph/warehouse200/cache`

**Please delete this folder!!!**

Then you can run it normally. Similarly, the other room settings have the same problem and answer. I hope the author can fix this bug!

If you want to create a map yourself, you need to do 3 steps:

1. Create one, similar to `src/tuw_multi_robot/tuw_multi_robot_demo/cfg/graph/warehouse200` , for example:

`src/tuw_multi_robot/tuw_multi_robot_demo/cfg/graph/warehouse300 `

2. Create one, similar to `src/tuw_multi_robot/tuw_multi_robot_demo/cfg/maps/warehouse200`, for example:

`src/tuw_multi_robot/tuw_multi_robot_demo/cfg/maps/warehouse300`

3. roslaunch run：

```
roslaunch tuw_multi_robot_demo demo.launch room:=warehouse300 nr_of_robots:=50
rosrun tuw_multi_robot_goal_generator goals_random _nr_of_robots:=50 _distance_boundary:=0.6 _distance_to_map_border:=0.2 _nr_of_avaliable_robots:=50
```
