### ISSUE TITLE
Using LaserScan data to avoid dynamic obstacle 

### ISSUE THREAD

**Issue by yashpatel1392** [tuw-robotics/tuw_multi_robot#36]
It appears that the package does not use any kind of sensor data from the robots for dynamic avoidance of obstacles not present in the map server. Is there any recommended way to implement local path planning or more complex navigation behavior within the multi-robot controller? Our group would like to test this package with physical robots but we require some form of obstacle avoidance.

**Comment by maxbader** [comment]
The demo was designed to present the capabilities of the multi robot routing, the local planer used is simple. But one can replace it with something which avoids obstacles. It was computational, not feasible to use a DWA or something more complex with hundreds of robots.
