### ISSUE TITLE
DXF to Graph converter creating an empty graphData file

### ISSUE THREAD

**Issue by esther-araujo** [tuw-robotics/tuw_multi_robot#42]
Hello!

I am new with CAD, and I was trying to create a new voronoi graph using a custom map.
So, I have downloaded LibreCAD, import a pgm file, draw the paths around the obstacles, and save the file as "segments.dxf":

![image](https://github.com/tuw-robotics/tuw_multi_robot/assets/40707889/23be51ab-c423-4e2e-b02e-863fdc6e9351)

Then, I launch the converter node as the tutorial said:

`roslaunch tuw_multi_robot_demo dxf_to_graph.launch dxf_name:=segments.dxf room:=simple_cave graph_name:=simple_cave`

And appears to be successful:

![image](https://github.com/tuw-robotics/tuw_multi_robot/assets/40707889/4164d35d-5353-409b-98aa-7727e46cab72)

But, when I tried to launch the custom graph, there is no voronoi graph in rviz:

![image](https://github.com/tuw-robotics/tuw_multi_robot/assets/40707889/55eb474f-6bd7-4022-ad6f-081c75e5d0e8)

When I checked the graphData file I found something like this: 

![image](https://github.com/tuw-robotics/tuw_multi_robot/assets/40707889/22c8d28c-df37-4491-b9e6-89db8cca87f1)

i.e. no vertex data was generated.

So, my question is: am I doing anything wrong in this process? What can I do to fix this situation?

Thank you very much in advance!

**Comment by maxbader** [comment]
Can you run a rostopic list (without rviz running) to see if the graph gets published?
It looks like you used free hand drawing in LibreCAD, you have to use lines!

**Comment by esther-araujo** [comment]
> Can you run a rostopic list (without rviz running) to see if the graph gets published? It looks like you used free hand drawing in LibreCAD, you have to use lines!

Hello, first thank you for the feedback. 
The graph gets published. The problem was really freehand drawing, I didn't know it needed to be with lines.
I redid the graph and it worked.
Thank you very much and congratulations for the work!!
