### ISSUE TITLE
DXF to Graph converter not creating a graph.launch file

### ISSUE THREAD

**Issue by corey-mitchell** [tuw-robotics/tuw_multi_robot#8]
Good afternoon,

I am quite new to ros and C++ and have no experience with CAD so sorry if this question is novice.

I am attempting to create a Custom Graph by following the [documentation](https://github.com/tuw-robotics/tuw_multi_robot/blob/master/tuw_multi_robot_demo/tutorials/demo_custom_graph.md) but seem to be doing something incorrectly.

I have downloaded LibreCAD and successfully imported a .pgm image into it. I then created a new layer and drew some simple lines around the obstacles. Like so:

![LibreCAD](https://user-images.githubusercontent.com/37916145/57111136-9e03fd80-6d00-11e9-98db-3cbec76ea4e4.png)

After drawing everything, I saved the file as ``` tuw_multi_robot_demo/cfg/dxf/$ROOM/$DXF_NAME.dxf ```, replacing $ROOM with 'suddath' and $DXF_NAME with 'suddath_warehouse'.

I then ran the converter node, like so:

```roslaunch tuw_multi_robot_demo dxf_to_graph.launch dxf_name:=suddath_warehouse.dxf room:=suddath graph_name:=suddath_graph ```

Here is the output, which appears to be successful:

![zzTUWError1](https://user-images.githubusercontent.com/37916145/57111479-d48e4800-6d01-11e9-977d-c694ca0f5c3d.png)

So now, I should be ready to use the graph. I attempt to do so by running the following command:

```roslaunch tuw_multi_robot_demo demo.launch room:=suddath map_name:=suddath_graph load_segments:=true```

This is where the following error occurs:

![zzTUWError2](https://user-images.githubusercontent.com/37916145/57111605-65652380-6d02-11e9-8c93-811bca13d2c0.png)

As you can see, the error is occurring because there is no graph.launch file inside of the 'suddath' directory. Which is correct, there is indeed no graph.launch file, however the ```tuw_multi_robot_demo/cfg/graph/$ROOM/cache/$GRAPH_NAME/``` directory was created and the graph data was saved to it as per the documentation.

My question then, is what, if anything, am I doing wrong? Furthermore, what steps can I take to rectify this situation?

Thank You.

P.S. It may be worth noting that I attempted to create my own graph.launch file utilizing the demo application's, but it simply started a blank world in rviz.

**Comment by anshulasimov** [comment]
what is missing is not the launch file but the .yaml file which specifies the parameters pertaining to the graph that has to be loaded. That being said the issue I'm facing is that despite the message saying that the graph has loaded , the graph cant be visualized in Rviz. This is a real problem that I'm facing (Will elaborate later)
